language: julia
os:
  - linux
    #  - osx
git:
  depth: 3
julia:
  - release
    #- nightly
matrix:
  allow_failures:
    - julia: nightly
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Example")'
  - if [ -f test/runtests.jl ]; then
      julia --check-bounds=yes -e 'Pkg.test("Example", coverage=true)';
    fi
  - mv doc/build doc/commited_build
  - ls doc
  - cat doc/commited_build/index.md
  - julia -e 'cd(Pkg.dir("Example")); include(joinpath("doc","make.jl"));'
  - ls doc
  - cat doc/commited_build/index.md
  - cat doc/build/index.md
  - diff -r doc/commited_build doc/build # check if the commited documentation is up-to-date
  - pwd
  - julia -e 'open("test","w") do file println(file,"some test content") end'
  - ls $PWD
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
